//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoVis.KnowledgeTrees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chapter()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int SubjectInLevelId { get; set; }
        public Nullable<int> SubjectFieldId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual Class Class { get; set; }
        public virtual SubjectInLevel SubjectInLevel { get; set; }
        public virtual SubjectField SubjectField { get; set; }
    }
}
