//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoVis.KnowledgeTrees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectInLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectInLevel()
        {
            this.Chapters = new HashSet<Chapter>();
        }
    
        public int LevelId { get; set; }
        public int SubjectId { get; set; }
        public int Id { get; set; }
        public string CurriculumName { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapter> Chapters { get; set; }
        public virtual Level Level { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
