//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoVis.KnowledgeTrees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicDependencyRelation
    {
        public int Id { get; set; }
        public int DependantId { get; set; }
        public int ReliesOnId { get; set; }
        public int Order { get; set; }
        public int DependencyRelationTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual Topic DependantTopic { get; set; }
        public virtual TopicDependencyRelationType TopicDependencyRelationType { get; set; }
        public virtual Topic ReliesOnTopic { get; set; }
    }
}
